---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hs0003173/public_html/

    # Pull the latest code
    - cd $DEPLOYPATH && git reset --hard origin/main && git pull origin main

    # Install dependencies
    - cd $DEPLOYPATH && npm install --omit=dev

    # Build Next.js project
    - cd $DEPLOYPATH && npm run build

    # Restart app (if using Node.js)
    - cd $DEPLOYPATH && pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
